# Generated by Django 5.0.3 on 2024-03-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videometadata',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='video',
            table='videos',
        ),
        migrations.AlterModelTable(
            name='videoasset',
            table='video_assets',
        ),
        migrations.AlterModelTable(
            name='videocaption',
            table='video_captions',
        ),
        migrations.AlterModelTable(
            name='videometadata',
            table='video_metadatas',
        ),
    ]
