version: '3'
services:
  webserver:
    container_name: webserver
    build:
      dockerfile: Dockerfile
      context: ./webserver
    restart: always # because it is routing traffic to our entire app
    ports:
      - 80:80 # setting port because nginx is the single entrypoint for entire application
  
  client:
    container_name: client
    build:
      dockerfile: Dockerfile
      context: ./client
    restart: on-failure
    env_file: ./env/client/.env.production

  backend:
    container_name: backend
    depends_on:
      - mongo
      - redis
    build:
      dockerfile: Dockerfile
      context: ./backend
    restart: on-failure
    env_file:
      - ./env/backend/.env.production

  mongo:
    container_name: mongo
    image: mongo:latest
    env_file:
      - ./env/mongo/.env.production

  redis:
    container_name: redis
    image: redis: latest